# hash:sha256:60103a955ce1a7d3aaa2fb98aa3525c074da450e3d9d9cb28bee509013526823
FROM registry.codeocean.com/codeocean/miniconda3:4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    matplotlib==3.9.4 \
    mpltern==1.0.4 \
    numpy==2.0.2 \
    openpyxl==3.1.5 \
    pandas==2.2.3 \
    scikit-learn==1.6.1 \
    seaborn==0.13.2
